# Generated by Django 5.0 on 2023-12-09 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200)),
                ('line3', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(choices=[('', 'Seleccionar departamento'), ('amazonas', 'Amazonas'), ('antioquia', 'Antioquia'), ('arauca', 'Arauca'), ('atlantico', 'Atlantico'), ('bolivar', 'Bolivar'), ('bogota D.C', 'Bogota D.C'), ('boyaca', 'Boyaca'), ('caldas', 'Caldas'), ('caqueta', 'Caqueta'), ('casanare', 'Casanare'), ('cauca', 'Cauca'), ('cesar', 'Cesar'), ('choco', 'Choco'), ('cordoba', 'Cordoba'), ('cundinamarca', 'Cundinamarca'), ('guainia', 'Guainia'), ('guaviare', 'Guaviare'), ('huila', 'Huila'), ('la guajira', 'La Guajira'), ('magdalena', 'Magdalena'), ('meta', 'Meta'), ('narino', 'Narino'), ('norte de santander', 'Norte de Santander'), ('putumayo', 'Putumayo'), ('quindio', 'Quindio'), ('risaralda', 'Risaralda'), ('san_andres', 'San Andres y Providencia'), ('santander', 'Santander'), ('sucre', 'Sucre'), ('tolima', 'Tolima'), ('valle del cauca', 'Valle del Cauca'), ('vaupes', 'Vaupes'), ('vichada', 'Vichada')], max_length=100)),
                ('street_type', models.CharField(choices=[('avenida', 'Avenida'), ('avenida_calle', 'Avenida Calle'), ('avenida_carrera', 'Avenida Carrera'), ('calle', 'Calle'), ('carrera', 'Carrera'), ('circular', 'Circular'), ('circunvalar', 'Circunvalar'), ('diagonal', 'Diagonal'), ('manzana', 'Manzana'), ('transversal', 'Transversal'), ('via', 'Vía')], max_length=50)),
                ('reference', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=10)),
                ('is_home_or_work', models.CharField(choices=[('home', 'Casa'), ('work', 'Trabajo')], max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
