# Generated by Django 4.2.7 on 2023-12-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0003_remove_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='department',
            field=models.CharField(choices=[('amazonas', 'Amazonas'), ('antioquia', 'Antioquia'), ('arauca', 'Arauca'), ('atlantico', 'Atlantico'), ('bolivar', 'Bolivar'), ('bogota D.C', 'Bogota D.C'), ('boyaca', 'Boyaca'), ('caldas', 'Caldas'), ('caqueta', 'Caqueta'), ('casanare', 'Casanare'), ('cauca', 'Cauca'), ('cesar', 'Cesar'), ('choco', 'Choco'), ('cordoba', 'Cordoba'), ('cundinamarca', 'Cundinamarca'), ('guainia', 'Guainia'), ('guaviare', 'Guaviare'), ('huila', 'Huila'), ('guajira', 'La Guajira'), ('magdalena', 'Magdalena'), ('meta', 'Meta'), ('narino', 'Narino'), ('norte_santander', 'Norte de Santander'), ('putumayo', 'Putumayo'), ('quindio', 'Quindio'), ('risaralda', 'Risaralda'), ('san_andres', 'San Andres y Providencia'), ('santander', 'Santander'), ('sucre', 'Sucre'), ('tolima', 'Tolima'), ('valle_cauca', 'Valle del Cauca'), ('vaupes', 'Vaupes'), ('vichada', 'Vichada')], max_length=100),
        ),
    ]
