# Generated by Django 4.2.7 on 2023-12-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0004_shippingaddress_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='ciudad',
        ),
    ]
