# Generated by Django 4.2.7 on 2023-12-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_image'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productos',
            field=models.ManyToManyField(through='carts.CartProductos', to='productos.producto'),
        ),
    ]
