# Generated by Django 4.2.7 on 2023-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='informacion_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.TextField(verbose_name='Correo')),
                ('telefono', models.IntegerField(max_length=10, verbose_name='Telefono')),
                ('cargo', models.TextField(verbose_name='Cargo')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('salario', models.IntegerField(verbose_name='Salario')),
                ('horas_trabajo', models.TextField(verbose_name='Horas Trabajo')),
                ('inicio_contrato', models.DateField(verbose_name='Inicio contrato')),
            ],
            options={
                'verbose_name': 'informacion_personal',
                'verbose_name_plural': 'informacion_personal',
                'db_table': 'personal',
                'ordering': ['id'],
            },
        ),
    ]
