# Generated by Django 4.2.7 on 2023-11-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_product_alter_informacion_personal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_personal',
            name='telefono',
            field=models.IntegerField(verbose_name='Telefono'),
        ),
    ]
