# Generated by Django 4.2.7 on 2023-11-07 23:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_informacion_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterModelOptions(
            name='informacion_personal',
            options={},
        ),
        migrations.AlterModelTable(
            name='informacion_personal',
            table=None,
        ),
    ]
