# Generated by Django 4.2.7 on 2023-11-08 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_informacion_personal_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
        ),
        migrations.RemoveField(
            model_name='informacion_personal',
            name='nombre',
        ),
        migrations.AddField(
            model_name='informacion_personal',
            name='nombres',
            field=models.CharField(default='', max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='informacion_personal',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='informacion_personal',
            name='correo',
            field=models.CharField(max_length=50, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='informacion_personal',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='informacion_personal',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo'),
        ),
    ]
