# Generated by Django 4.2.7 on 2023-11-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cargo_remove_informacion_personal_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion_personal',
            name='imagen',
            field=models.ImageField(null=True, upload_to='informacion_personal'),
        ),
    ]
