# Generated by Django 4.2.7 on 2023-11-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_informacion_personal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_personal',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
