# Generated by Django 4.2.7 on 2023-11-14 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, verbose_name='Categoria:')),
            ],
        ),
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedores', models.CharField(max_length=50, verbose_name='Proveedor:')),
                ('razon_social', models.TextField(verbose_name='Razon social:')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion:')),
                ('telefono', models.IntegerField(verbose_name='Telefono:')),
                ('Correo', models.CharField(max_length=40, verbose_name='Correo Electronico:')),
                ('inicio_contrato_proveedores', models.DateField(verbose_name='Inicio contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_categoria', models.TextField(max_length=200, verbose_name='Descripcion:')),
                ('nombre_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('nombre_proveedores', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='informacion_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('salario', models.IntegerField(verbose_name='Salario')),
                ('horas_trabajo', models.TextField(verbose_name='Horas Trabajo')),
                ('inicio_contrato', models.DateField(verbose_name='Inicio contrato')),
                ('imagen', models.ImageField(null=True, upload_to='media')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad:')),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('Inventario_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventario', verbose_name='Producto:')),
            ],
        ),
    ]
