# Generated by Django 4.2.7 on 2023-11-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_image'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='productos',
            field=models.ManyToManyField(blank=True, to='productos.producto'),
        ),
    ]
